//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAdmin.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayReport
    {
        public int id { get; set; }
        public Nullable<System.DateTime> DayReport1 { get; set; }
        public Nullable<int> TotalMedicines { get; set; }
        public Nullable<int> TotalPatients { get; set; }
        public Nullable<int> TotalInvoice { get; set; }
    }
}
