//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAdmin.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Has_role
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int roleId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Role Role { get; set; }
    }
}
