//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAdmin.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<double> ExaminationFee { get; set; }
        public Nullable<double> DrugFee { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<int> PrescriptionId { get; set; }
    
        public virtual Prescription Prescription { get; set; }
    }
}
