//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAdmin.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Medicine
    {
        public int id { get; set; }
        public int MedicineId { get; set; }
        public int InvoiceId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Usage { get; set; }
        public Nullable<int> NumOfUse { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Medicine Medicine { get; set; }
        public virtual UnitMedicine UnitMedicine { get; set; }
        public virtual UsageMedicine UsageMedicine { get; set; }
    }
}
