//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicAdmin.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription_Medicine
    {
        public int Id { get; set; }
        public Nullable<int> PrescriptionId { get; set; }
        public Nullable<int> MedicineId { get; set; }
        public Nullable<int> AmountDrug { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Usage { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Prescription Prescription { get; set; }
        public virtual UnitMedicine UnitMedicine { get; set; }
        public virtual UsageMedicine UsageMedicine { get; set; }
    }
}
